### ISSUE TITLE
.gitattributes

### ISSUE THREAD

**Issue by olehsamoilenko** [natqegu/RT#1]
Hi team. I have a piece of advice for you;)

To prevent the incorrect programming language detection (_Roff insted of C_) it's smart to use **.gitattributes** file with the following rule:

`maps/*.3ds linguist-vendored`

It tells to github that this folder is 'vendored', isn't a part of the code, and must not be contributed between another languages in your project. RT is not written in Roff, right? As well as my Corewar was't written is Assembly, but github thought so:)

![image](https://user-images.githubusercontent.com/30492641/66390393-45354100-e9d3-11e9-91e0-5c7303fbb10e.png)

![image](https://user-images.githubusercontent.com/30492641/66390466-6138e280-e9d3-11e9-9cbf-8dd4ddd11c92.png)

It will make your repo more cute and presentable for other students and open-source lovers

Thanks for your attention. I'm appreciated of looking over your project ._.

**Comment by natqegu** [comment]
Thank you for that tip, it looks much more nice this way!
